services:
  ai-app-laboratory:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
    image: ai_app_laboratory_image
    container_name: ai_app_laboratory_container
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ~/code/python/github.com/yshujie/ai-app-laboratory:/opt/ai-app-laboratory
    working_dir: /opt/ai-app-laboratory
    network_mode: "bridge"