version: '3.8'
services:
  user-portrait-artist:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_portrait_artist_image
    container_name: user_portrait_artist_container
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ~/code/python/github.com/yshujie/user-portrait-artist:/opt/user-portrait-artist
    working_dir: /opt/user-portrait-artist
    depends_on:
      - mongodb
    networks:
      - ai-app-network

  mongodb:
    image: mongo:latest
    container_name: user_portrait_artist_mongodb_container
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai-app-network

volumes:
  mongodb_data:

networks:
  ai-app-network: